### ISSUE TITLE
token support

### ISSUE THREAD

**Issue by mreinstein** [remy/now-no-alias#3]
@remy would you accept a PR to add an ability like 

```bash
now-no-alias --token=abcdef123....
```

I manage several client's `now` accounts, and tokens are big part of the workflow.

**Comment by remy** [comment]
Absolutely

**Comment by mreinstein** [comment]
@remy some follow up questions before I slam a PR together:

* do you have thoughts on how you'd like to support these arguments? Right now the arg handling for this tool is pretty minimal. Specific modules you like for this? Prefer direct raw `argv` handling?

* Is there an undocumented `filter` feature?

**Comment by mreinstein** [comment]
I answered my own question above re: the `filter` feature...looks like it's possible to optionally filter by a specfic deployment name.
